#spring.application.name=board

# server port
server:
  port: 8080
  servlet:
    session:
      tracking-modes: cookie # URL에 jsessionid 가 노출되지 않도록 함
      timeout: 1800 #세션 타임아웃 (1800초)

# database
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/item?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
  # 메세지, 국제화
  messages:
    basename: messages,errors
    encoding: UTF-8
  thymeleaf:
    cache: false
    prefix: classpath:/templates/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  #xml Alias 없애기
  configuration:
    map-underscore-to-camel-case: true


