#spring.application.name=board

# server port
server:
  port: 8080

# database
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/item?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
  #메세지, 국제화
  messages:
    basename: messages,errors
    encoding: UTF-8
  thymeleaf:
    cache: false
    prefix: classpath:/templates/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  #xml Alias 없애기
  configuration:
    map-underscore-to-camel-case: true


